theme: jekyll-theme-slate
title: TX-2 Project
description: Re-creating the historically important TX-2 computer
markdown: kramdown
plugins:
  - jekyll-readme-index
  - "jekyll-github-metadata"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
